### ISSUE TITLE
Change in LAU website layout?

### ISSUE THREAD

**Issue by AHoerner** [keberwein/blscrapeR#1]
Hi Kris! I tried to run your vignette code for a Florida county unemployment map, replacing Florida with  Ohio. I got this result:

trying URL 'http://www.bls.gov/lau/laucntycur14.txt'
Error in download.file("http://www.bls.gov/lau/laucntycur14.txt", temp) : 
  cannot open URL 'http://www.bls.gov/lau/laucntycur14.txt'
In addition: Warning message:
In download.file("http://www.bls.gov/lau/laucntycur14.txt", temp) :
  cannot open URL 'http://www.bls.gov/lau/laucntycur14.txt': HTTP status was '404 Not Found'

This seems to be an issue with redesign of the LAU website, rather than your code per se. When I entered the URL above manually, I got the same error.

If you figure out where these files have moved, I wouldn't mind knowing what it is. Thanks!

Andrew Hoerner
TowardVictory@gmail.com

**Comment by keberwein** [comment]
@AHoerner, you were right, the BLS changed the URL on us. Fortunately, I was able to find where they moved it pretty quickly. The following code now works. If you need this right away, you can do a `devtools::install_github("keberwein/blscrapeR")` I won't be pushing this to CRAN until next week.

BTW, the new URL is: http://www.bls.gov/web/metro/laucntycur14.txt

```
library(blscrapeR)
df <- get_bls_county(stateName = "Ohio")

bls_map_county(map_data=df, fill_rate = "unemployed_rate", 
               stateName = "Ohio")

```

![ohiounemp](https://cloud.githubusercontent.com/assets/8354988/18995125/e3085b60-86f8-11e6-811d-7633f8568937.png)

**Comment by keberwein** [comment]
The fix for this has been pushed to CRAN as of v.1.01.  You should update `update.packages("blscrapeR")`
