### ISSUE TITLE
blscrapeR functions return function syntax instead of data

### ISSUE THREAD

**Issue by alex-arthur** [keberwein/blscrapeR#13]
I was using this package yesterday evening and the code was working correctly by returning the actual data.
This morning, I noticed that my code was no longer working. The code is below.

```
library(devtools)
devtools::install_github("keberwein/blscrapeR")
library(blscrapeR)
bls_api("CUUR0000SA0", startyear = "2010", endyear = "2017")
```
The returned output is: 

> function (x, df1, df2, ncp, log = FALSE) 
{
    if (missing(ncp)) 
        .Call(C_df, x, df1, df2, log)
    else .Call(C_dnf, x, df1, df2, ncp, log)
}
<bytecode: 0x00000000087bc150>
<environment: namespace:stats>

**Comment by keberwein** [comment]
I am unable to reproduce the error on my end. Try installing the package from CRAN instead of the development version `install.packages("blscrapeR")`. Also, make sure your `httr` and `jsonlite` packages are up to date `update.packages(c("httr", "jsonlite"))`.

**Comment by alex-arthur** [comment]
Thanks keberwein. I'm not sure why I was getting the error. I tried installing from CRAN instead just using `install.packages("blscrapeR")`, but it was still having issues. I updated everything (packages and software) hoping that would fix the issue, but it still gave me a function instead of data. As a last resort, I used R Studio's built in package installer under Tools, and for whatever reason, it started working fine again. 
I appreciate your quick reply. Thanks again!

**Comment by smitty1788** [comment]
Hello,

I'm running to this same error.

```
library(tidyverse)
library(blscrapeR)

msa <- read.delim("https://raw.githubusercontent.com/smitty1788/Personal-Website/master/dl/MSA_Codes.txt",
                header = FALSE) %>% 
  rename(area_code = V2, area_text = V3) %>% 
  select(area_code, area_text) %>% 
  mutate(CBSA_ID = substr(area_code, 5, 9))

MSA_LAUS <- tibble(date = character(),
                   labor_force = numeric(),
                   employment = numeric(),
                   unemployment = numeric(),
                   unemployment_rate = numeric(),
                   CBSA_ID = character(),
                   area_text = character())

for (i in 1:395) {
  ac <- as.character(msa$CBSA_ID[i])
  at <- as.character(msa$area_text[i])
  
  labor_force <- as.character(paste0("LAU", msa$area_code[i], "06"))
  employment <- as.character(paste0("LAU", msa$area_code[i], "05"))
  unemployment <- as.character(paste0("LAU", msa$area_code[i], "04"))
  unemployment_rate <- as.character(paste0("LAU", msa$area_code[i], "03"))
  
  x <- as.vector(c(labor_force, employment, unemployment, unemployment_rate))
  series_id <- tibble(
    name = c("labor_force", "employment", "unemployment", "unemployment_rate"),
    id = c(labor_force, employment, unemployment, unemployment_rate)
  )
  
  labor <- bls_api(x, startyear = '2002', endyear = '2010')
  laus <- labor %>% 
    mutate(seriesID = as.character(seriesID)) %>% 
    merge(series_id, by.x = 'seriesID', by.y = 'id', all.x = TRUE) %>%
    filter(!is.na(name)) %>% 
    select(year, periodName, name, value) %>% 
    spread(name, value = value) %>% 
    mutate(date = as.Date(paste0(as.character(year), " ", as.character(periodName), " ", "01"), '%Y %B %d'),
           CBSA_ID = ac,
           area_text = at) %>% 
    select(date, labor_force, employment, unemployment, unemployment_rate, CBSA_ID, area_text)
  
  MSA_LAUS <- rbind(MSA_LAUS, laus)
}
```

The error returns as 
```
Error in UseMethod("mutate_") : 
  no applicable method for 'mutate_' applied to an object of class "function"
```

**Comment by keberwein** [comment]
First thing I noticed is you don't have your BLS API key set in the `bls_api()` function. With no api key, the query limit set by the BLS is 25 per day. Your loop is running 395, and exceeding that limit. 

I set a key argument with `labor <- bls_api(x, startyear = '2002', endyear = '2010', registrationKey = Sys.getenv("BLS_KEY"))` and everything worked as expected. It should be noted that even with an API Key, the daily limit is 500 requests, which doesn't leave a whole lot of overhead for R&D. If you need help getting and setting your API key, see the [README](https://github.com/keberwein/blscrapeR) for more details.

My output data file of the successful run is attached if that helps you.

[msa_laus.RData.zip](https://github.com/keberwein/blscrapeR/files/1399708/msa_laus.RData.zip)

**Comment by smitty1788** [comment]
keberwein, I set the API key as detailed. I am still running into the same issues. I have been running the for loop with just a small range 1:10 or 1:20, for development, so I can't imagine I've run into API limits very quickly.  I have also reinstalled the package through cran, same issues.
