### ISSUE TITLE
Pulling Annual QCEW Information

### ISSUE THREAD

**Issue by jessefthomas** [keberwein/blscrapeR#14]
Hi, first time poster so please forgive any ignorance :). I'm taking a class on R now. 

BLS provides annual averages for the QCEW information. This vignette is helpful for what I'm trying to get at. But I've only been able to pull down qrtly information. BLS also has annual averages (https://www.bls.gov/cew/datatoc.htm), is there a way to pull those with this package as well? Thanks.

**Comment by keberwein** [comment]
That was an oversight on my part. Luckily, it was a really easy fix. You'll have to reinstall the package from the Github for now. I'll try to get this pushed to CRAN next week. Glad you find it useful BTW!

The argument for annual is `"A"` instead of a numeric.

```
# Force reinstall
devtools::install_github("keberwein/blscarpeR", force=T)

library(blscrapeR)
dat <- qcew_api(year=2015, qtr="A", slice="industry", sliceCode=5112)
```

**Comment by jessefthomas** [comment]
Amazing! Thanks for the quick response.  I did get an error on the install, perhaps there is a new URL?

```
> devtools::install_github("keberwein/blscarpeR", force=T)
Downloading GitHub repo keberwein/blscarpeR@master
from URL https://api.github.com/repos/keberwein/blscarpeR/zipball/master
Installation failed: Not Found (404)
```

**Comment by keberwein** [comment]
I would help if I learned how to spell my own package name correctly!

`devtools::install_github("keberwein/blscrapeR", force=T)`

Sorry, It's been a long week!

**Comment by jessefthomas** [comment]
Thanks. This package is helping my organization not have have sift through literally 45,000 excel files to find the information they want.

**Comment by keberwein** [comment]
LOL, the BLS data landscape is overwhelming. Thanks so much for pointing out the bug. Glad you find the package useful; that's why I wrote it! FYI: I'm closing this issue, but you can expect to see the changes in the next official CARN release, next week or so.
