### ISSUE TITLE
startyear and endyear issues

### ISSUE THREAD

**Issue by iryboto** [keberwein/blscrapeR#20]
It seems that when selecting years, the maximum range is 9 years. 

For example,

bls_api("LAUCT360100000000003", startyear=2003, endyear=2016)

produces data from 2003.M1 to 2012.M12.

However, data for 2013.M1 to 2016.M12 exists, i.e.

bls_api("LAUCT360100000000003", startyear=2013, endyear=2016)

gives the required data from 2013-2016.

**Comment by keberwein** [comment]
Yes, that is the query limit if you don't register an API key with the BLS. The limit for key-holders is 20 years.

See the "API Keys" section of the [README file](https://github.com/keberwein/blscrapeR/blob/master/README.md). After installing your key, the following returns the expected result.

```
bls_api("LAUCT360100000000003", startyear=2003, endyear=2016, Sys.getenv("BLS_KEY"))
```
