### ISSUE TITLE
"A" vs "a" in annual data

### ISSUE THREAD

**Issue by camille-s** [keberwein/blscrapeR#22]
First off, I really appreciate this package. I was having a bit of a struggle getting annual data. The docs say to use `qtr = "A"`, but I get an error; if I use `qtr = "a"`, it comes through okay. Likewise, going to the URL https://data.bls.gov/cew/data/api/2017/A/area/09009.csv gets me a "Not found" error, but with a lowercase `a` it's fine. I'm not sure if this is something that changed in the API on their end.

``` r
library(blscrapeR)

nhv1 <- qcew_api(year = 2017, qtr = "a", slice = "area", sliceCode = "09009")
#> Please set a numeric year.
#> Trying BLS servers...
#> Payload successful.
nhv2 <- qcew_api(year = 2017, qtr = "A", slice = "area", sliceCode = "09009")
#> Please set a numeric year.
#> Trying BLS servers...
#> URL caused a warning. Please check your parameters and try again: https://data.bls.gov/cew/data/api/2017/A/area/09009.csv
#> Error in qcew_api(year = 2017, qtr = "A", slice = "area", sliceCode = "09009"): object 'qcewDat' not found
```

**Comment by keberwein** [comment]
Glad you're finding the package useful, and thanks so much for the bug report. I'm going to patch this in the next few days, shouldn't be a huge deal. I'll leave this open until I make the commit.

**Comment by keberwein** [comment]
I made that fix and went ahead and pushed it to CRAN. You can install the new version from there. Thanks again for pointing out the bug!

`install.packages("blscrapeR")`
