### ISSUE TITLE
blscrapeR not on CRAN

### ISSUE THREAD

**Issue by kerr14333** [keberwein/blscrapeR#24]
Hey, first, wanted to say that I love your package. I work at BLS and recommend it to anyone looking to pull BLS data in R over the one we have on our website.

Second was wondering why it's not on CRAN? I forked the package and tried devtools::check() and pandoc is throwing errors (below) when trying to build the vignette. I was wondering if this is the reason its not published and if you have been having this experience.

```
E  creating vignettes (17.9s)OR
   
   Access violation in generated code when reading 0x8a07568
   
    Attempting to reconstruct a stack trace...
   
      Frame	Code address
    * 0x22daf0	0x4018450 C:\Users\GRIEVE~1\DOCUME~1\RSTUDI~1.120\bin\pandoc\pandoc.exe+0x3c18450
    * 0x22daf8	0x231790
   
   Error: processing vignette 'Mapping_BLS_Data.Rmd' failed with diagnostics:
   pandoc document conversion failed with error 11
   Execution halted
Error in processx::run(bin, args = real_cmdargs, stdout_line_callback = real_callback(stdout),  : 
  System command error
```

I saw something that might be related in an issue tracker having to do with the version of Pandoc being used https://github.com/rstudio/rstudio/issues/3661

**Comment by keberwein** [comment]
Yes, it's not a Pandoc issue though. There's a bad hyperlink in the vignettes. I'm a Hadoop Engineer in my other life and work has kept me too busy to fix it. I'm going through the hyperlinks now, so hopefully I can have it back on CRAN in a few days.

**Comment by kerr14333** [comment]
No problem, it’s no rush. I understand how work gets busy. I just noticed it the other day while referring someone. Thanks for the quick response.

**Comment by keberwein** [comment]
We're back on CRAN now, thanks again for the heads-up!

**Comment by kerr14333** [comment]
No problem, thanks again for your work on this. It's a great package.
