### ISSUE TITLE
CRAN?

### ISSUE THREAD

**Issue by cdeterman** [keberwein/blscrapeR#31]
I see that this package was removed from CRAN in July (https://cran.r-project.org/web/packages/blscrapeR/index.html).  Are there any plans for the issues to be resolved and resubmitted?  Or should users plan to go primarily to this repo?

**Comment by keberwein** [comment]
Yes, I do have plans to re-submit to CRAN. This has always been more of a hobby project for me, and these days I'm writing way more Java/Scala than R, but I want to keep it going. I haven't  even run CRAN check on this yet, but I'm pretty sure it's a dead hyperlink in the documenting (CRAN is weird like that.) No concrete timetable as of now.On Sep 13, 2021 2:38 PM, Charles Determan ***@***.***> wrote:
I see that this package was removed from CRAN in July (https://cran.r-project.org/web/packages/blscrapeR/index.html).  Are there any plans for the issues to be resolved and resubmitted?  Or should users plan to go primarily to this repo?

**Comment by sawyervillers** [comment]
This is a useful package if you get time to resubmit.

**Comment by keberwein** [comment]
Just an FYI here. This package should be back on CRAN in the next couple of weeks. I will update this ticket and close it once it is. However, if you ever need to install an R package not on CRAN, you can always install directly from GitHub via the `devtools` package. I finally have some time to work on this again, so hopefully we'll see a few different minor releases this year. 

```
# Update dependencies
install.packages("rlang")
install.packages("devtools")

devtools::install_github("keberwein/blscrapeR")
```

**Comment by keberwein** [comment]
Good news gang, this package is now back on CRAN. I'm closing this issue. I'm hoping to have a couple of minor releases in the coming year. 

If this, or any other package ever disappears from CRAN, remember you can still use the `devtools` package to install directly from Github.

`devtools::install_github("keberwein/blscrapeR")`

Thanks for your support!
