### ISSUE TITLE
Internal Datasets for Series Codes

### ISSUE THREAD

**Issue by cdeterman** [keberwein/blscrapeR#32]
If there is an interest in continuing this package, I think it would be useful to have the series id code groups contained in internal datasets.  Such as the super sector codes [here](https://download.bls.gov/pub/time.series/ce/ce.supersector).  That said, at a bare minimum, have the documentation point to the BLS documentation for creating these codes [here](https://www.bls.gov/help/hlpforma.htm).

**Comment by keberwein** [comment]
This feature was added several years ago. Try the following line of code. If no data sets appear, you may have to update your version.

`data(package='blscrapeR')`
