### ISSUE TITLE
Adding CPI series to `series_ids`

### ISSUE THREAD

**Issue by adhi-r** [keberwein/blscrapeR#37]
Hi,

Can we get CPI series (e.g. CUSR0000SA0) added to the data frame?

Or, if you can just point me to where I can find a formatted spreadsheet with the id's and the names, I can do the work of adding a df for it and submit a PR. Maybe I'm dumb but I truly can't find a spreadsheet that has the CPI codes labeled nicely.

**Comment by keberwein** [comment]
Hey @adhi-r. I don't think I'm real clear on your ask. If I run the code below, the returned dataframe has the seriesID as the last column. Where you asking for something else? Perhaps you meant the seriesID description?
```
library(blscrapeR)
df <- bls_api("CUSR0000SA0")
```

**Comment by adhi-r** [comment]
Oh sorry, I was referring to the "search_ids" feature. It'd be neat to be able to use that for CPI.
