### ISSUE TITLE
Out of date for R 4.2.2

### ISSUE THREAD

**Issue by danmika** [keberwein/blscrapeR#38]
I'm trying to install this package using R 4.2.2, getting the following error:

```
Warning in install.packages :
  package ‘blscrapeR’ is not available for this version of R

A version of this package for your version of R might be available elsewhere,
see the ideas at
https://cran.r-project.org/doc/manuals/r-patched/R-admin.html#Installing-packages
```

When installing via devtools:

```
Installing package into ‘C:/Users/danmi/AppData/Local/R/win-library/4.2’
(as ‘lib’ is unspecified)
* installing *source* package 'blscrapeR' ...
** using staged installation
** R
** data
*** moving datasets to lazyload DB
** byte-compile and prepare package for lazy loading
Error in loadNamespace(i, c(lib.loc, .libPaths()), versionCheck = vI[[i]]) : 
  namespace 'rlang' 1.0.6 is already loaded, but >= 1.1.0 is required
Calls: <Anonymous> ... asNamespace -> loadNamespace -> namespaceImport -> loadNamespace
Execution halted
ERROR: lazy loading failed for package 'blscrapeR'
* removing 'C:/Users/danmi/AppData/Local/R/win-library/4.2/blscrapeR'
Warning: installation of package ‘C:/Users/danmi/AppData/Local/Temp/Rtmpg3muiy/file828125135fc/blscrapeR_3.2.2.tar.gz’ had non-zero exit status
```

Is there a way to install this on the latest version of R? Or do I need to revert to an older version? If so, which is the most recent version of R that's compatible?

**Comment by keberwein** [comment]
Try upgrading your rlang package and install from devtools again. That should work for now until I get it relisted on CRAN.

`install.packages("rlang")`
`devtools::install_github("keberwein/blscrapeR")`

**Comment by danmika** [comment]
> Try upgrading your rlang package and install from devtools again. That should work for now until I get it relisted on CRAN.
> 
> `install.packages("rlang")` `devtools::install_github("keberwein/blscrapeR")`

Perfect, thanks! I had to dig into some firewall issues to get rlang to update, but that did the trick.

**Comment by keberwein** [comment]
Thanks for the report. I was't actually aware if got kicked off CRAN (for whatever reason.) I can go ahead and fix that now. So, thank you!
